-- 鹏伟家居订单后台数据库表
-- 在 Supabase → SQL Editor 里执行本文件。

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  order_no text not null unique,
  customer_name text not null,
  customer_phone text not null,
  customer_address text not null,
  customer_note text,
  items jsonb not null default '[]'::jsonb,
  total_amount numeric(10,2) not null default 0,
  status text not null default '待联系'
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  page_url text,
  user_agent text
);

alter table public.orders enable row level security;
alter table public.events enable row level security;

-- 访客可以提交订单和浏览事件
drop policy if exists "public insert orders" on public.orders;
create policy "public insert orders" on public.orders for insert to anon with check (true);

drop policy if exists "public insert events" on public.events;
create policy "public insert events" on public.events for insert to anon with check (true);

-- 登录后的管理员可以查看和更新订单、查看访问数据
drop policy if exists "admin select orders" on public.orders;
create policy "admin select orders" on public.orders for select to authenticated using (true);

drop policy if exists "admin update orders" on public.orders;
create policy "admin update orders" on public.orders for update to authenticated using (true) with check (true);

drop policy if exists "admin select events" on public.events;
create policy "admin select events" on public.events for select to authenticated using (true);
